ESGF/esgf-installer

esg-init
This version fixes the problems I was having with the thredds reinit and index publishing.
thredds.py switch to httplib + basic auth in header.
=> up publisher version

esg-purge.sh
I suspect Globus is not being properly uninstalled, but these fixes are necessary to purge solr and postgresql properly -- failure of the latter will completely break the current installer.
=> Properly purge postgresql, cdat, and solr

esg-node, globus/esg-globus
The pull request includes changes in test functions required after moving from Globus tarball to Globus RPMs. It also add a test data file for a test GridFTP download.
Globus can be tested directly:
esg-node --test-globus end-user
or as a part of publication test:
esg-node --test-pub
=> Fix Globus tests

esg-purge.sh
This removes the default purge with no options specified, adds a help message, and reverts a bad commit that had redundant deletions and would delete all source repositories including this script.
=> esg-purge.sh fixes

globus/esg-globus
I added gridftp_server_port=2811 back. I will remove it later after making sure that it is not used by other scripts. This variable is not needed, the same as we do not have any variables specifying that port 80 is a port for HTTP, or port 443 is for HTTPS.
=> Add End-user GridFTP port number back

cog/esg-cog
According to [PEP470](http://legacy.python.org/dev/peps/pep-0470/) and [this PYPI ticket](https://bitbucket.org/pypa/pypi/issues/365/many-packages-have-empty-list-of-links) projects that do not host their files at pypi.python.org are not available through the Simple API anymore. *esg_cog* fails to install correctly because of this missing dependency. A manual install fixes the installation process.
=> Install PIL package for cog manually

globus/esg-globus
The globus-connect-server-*setup script checks if a new version of Globus Connect Server (GCS) is available, and if it is, the script prints a warning about it and exits what causes the installer failure. The esg-globus does not update installed GCS automatically what leads to the described installer failure. The fix updates installed GCS to avoid the situation.
=> Update Globus Connect Server if already installed

esg-node
Fix a line that is breaking "--update" with an index-only node. Even if for the call to get_webxml_file there is no condition on $((sel & INSTALL_BIT)), it should still be conditional on the data component having been selected. If not a data node, it can do nothing useful, and in fact breaks the script because it tries to download the web.xml file to a non-existent local directory.
=> do not update THREDDS web.xml if not a data node

esg-autoinstall
This gets run twice during a fresh install for --type all (once for
gateway, once for datanode), but the second time the prompt will
default to N because it detects an existing Globus installation.  This
has to be forced Y, or a number of packages will not get installed and
the Globus user will not get created.
=> Force Globus installation to Y at all times

esg-node
This function exists to prevent esg-node from clobbering files
symlinked into git repositories because they're under active
development, but there isn't any point in preventing creation of files
that do not yet exist.
=> _is_in_git() will not return true for nonexistent targets

esg-autoinstall, globus/esg-globus
The installer will ask an additional question:
- "Do you want to register the MyProxy server with Globus?" on the idp node,
- "Do you want to register the GridFTP server with Globus?" on the data node.
When an admins replies 'Y', the installer will run Globus Connect Server setup script that generates all configuration files for MyProxy/GridFTP server and will create a Globus endpoint corresponding to the MyProxy/GridFTP server. If an admin replies 'N', the installer will create MyProxy/GridFTP server configuration files that are equivalent to those created by GCS setup scripts.
=> Make registration of MyProxy/GridFTP servers with Globus optional

esg-autoinstall, esg-gitstrap, esg-node
Most notably, this fixes the problem with esg-autoinstall not running the final psql command in esg-node due to the last output text occurring before the command is run, and makes esg-gitstrap by default produce an environment much closer to esg-bootstrap.
=> Fixes to esg-gitstrap and esg-autoinstall

esg-autoinstall, jar_security_scan
This fixes two unhandled prompts that only show up during upgrades, and also updates the jar security scanner for 2.4.4-devel, with all known false positives cleared.
=> jar security scanner and esg-autoinstall upgrade fix

esg-node
To allow for the possibility that certificates lack a newline at the end of the file (on the "END CERTIFICATE" line), add an extra newline after each one when concatenating into a bundle. In the event that a newline already exists, it will add a harmless blank line, but if it does not, then this will avoid an error in which the line gets joined to the "BEGIN CERTIFICATE" line of the next file.
=> add extra newline between certificates

globus/esg-globus
The fix sets AUTHSERVICE to esgf property orp.security.authorization.service.endpoint instead of myproxy_endpoint or, if myproxy_endpoint is not set, to esgf_host.
=> Fix AUTHSERVICE endpoint URL on data nodes

esg-init, esg-node
The variable `cdat_home` is set in the installer to point to the root conda environment rather than the esgf-pub one.  This seems to be causing various problems.  The root conda environment is never activated in any of the scripts, so no software gets installed into it.  Only the esgf-pub conda environment is activated.
This pull request modifies the value of `cdat_home` to point to `/usr/local/conda/envs/esgf-pub` instead of `/usr/local/conda`.
`$cdat_home` is used in various places, of which it seems that the only places where it is needed to point to the root env are:
* where used in `esg-node` when first setting up miniconda -- which is modified accordingly in this pull request.
* a line in `clean_node_manager_database_subsystem_installation`, which I will modify in a separate pull …
=> point cdat_home at a more appropriate location (the esgf-pub conda environment)

esg-init, esg-node
Reverts ESGF/esgf-installer#275  I don't think we want to change $cdat_home - $conda_home would be a better name for it now, but that is too cumbersome.  Better to switch the rms to delete the right path.
=> Revert "point cdat_home at a more appropriate location (the esgf-pub conda environment)"

esg-node
this code will allow the install on centos7 /redhat 7
I have remove the unused DIST variable
and the format of /etc/redhat-release is changed in centos7, so I need to add the awk filter
=> allow install of centos 7

esg-node
One line added to call the esg-auth script, https://github.com/ESGF/esgf-auth/blob/master/bin/esg-auth, that downloads and sets up the ESGF Auth Client (Django webapp), https://github.com/ESGF/esgf-auth.
The new authorization filter in TDS, esg.orp.app.AuthenticationRedirectFilter, redirects a user web browser to the ESGF Auth client when a user clicks an HTTP download link to download a dataset file. From the user perspective the ESGF Auth client acts the same way as ORP. It lets a user select an IdP and then the Auth client redirects the user to the selected IdP. The Auth client detects whether the IdP supports OAuth2 or OpenID only. OAuth2 is preferable authentication/authorization protocol between the Auth client and the IdP.
=> Set up the ESGF Auth client to a data node

esg-functions
With the master mirror not being available the out-of-sync check evaluates to true and the script tries to use the not available master mirror.
This change should make it fallback only if it is reachable.
=> Keep fastest mirror if master is not available

base/esg_setup.py, esgf_utilities/esg_cli_argument_manager.py, tests/test_esg_setup.py
Since check_prerequisites is invoked in the main function of esg_node, there is no need to make these checks again. Additionally, the FQDN is verified by the user in the questionnaire.
esg_setup is becoming smaller and smaller. Soon it may have its functionality relocated and be removed all together.
=> Esg setup cleanup

base/esg_java.py, esgf_utilities/pybash.py
It is unclear what distutils.spawn.find_exectutable was doing to
determine the path and if the file existed. It would return None,
causing problems with the version check. This way the existence and
type is verified in a transparent way. Some cleanup was done to
adhere to PEP8.
This references issue #471
=> Replace find_executable with pybash.is_exe for transparency

esgf_utilities/esg_functions.py
This is to likely resolve #494 by removing excess spaces/newlines from the string read from the file.
=> Clean the postgres password upon retrival

filters/esg_security_tokenless_filters.py
This system for installing these jar files seems highly unstable.
Should it not be as simple as pull all the needed .jar files from
the distribution mirro and copy them into their respective
locations? Why are they going into orp and then later being copied
to thredds? Also, the names of the files are hardcoded? What if the
version in the mirror changes or a jar is no longer needed? Unless
I am missing something this could use a significant overhaul.
=> Add log4j.jar installation

base/esg_postgres.py
This change from ident to md5 must happen after the super user is created and, for now, after the database is created, but before passwords start being used as authentication for connections to the database.
=> The timing of this replacement is very particular

data_node/thredds.py, esgf_utilities/esg_questionnaire.py
This will conflict with None being an invalid value for this
property and will need to be fixed in the future. Additionally,
add a try/except check where the property is used. This was
originally made to solve #486 and #487 because they were 
thought to be similar, but #487 turned out to be a separate 
issue.
=> Set default mail.admin.address to None

requirements.txt
cdf2cim is listed as a requirement in setup.py of esgcet (the
publisher) and will be installed there. This will resolve the
version conflict issue that has been encountered. This is
to resolve #507
=> Remove the installation of cdf2cim in bootstrapper

base/esg_postgres.py, base/postgres_conf/pg_hba.conf
The original pg_hba.conf would work throughout the installer. These
changes keep those features, but add a fix for the post-install
failure case.
=> Recreate original working pg_hba, but add IPv4 localhost entry

base/esg_apache_manager.py, data_node/esg_publisher.py, esg_bootstrap.sh, esg_node.py, esgf_utilities/esg_functions.py, index_node/esg_cog.py, tests/test_pip.py
With the use of plumbum it is easier to use the pip executable to make installations. This is especially true as pip does not officially support being imported and used in that way for installations. This is related to #512 and #510 .
=> Pip install

esg_purge.py
Remove instances of stream_subprocess_output from esg_purge where possible.  One instance is left when purging_solr as I have not converted that function to use call_binary() yet
=> Plumbum esg purge

base/esg_tomcat_manager.py
Since `server.xml` lives within the repository there is no need to pull the version from the mirror. The functionality of the mirror template can also be removed. The ports check is not currently being used, but may be a good idea to have as a way to do a verification at the end.
=> Cleanup deprecated functionalities

esg_init.py, idp_node/idp.py, index_node/esg_search.py
While there is more opportunities for simplification here, this is
a good start to moving towards using the Github repos as an
alternative to the distribution mirrors.
=> Use esgf-config repo to retreive missing static.xml files

esg_node.py
The esg_dashboard.setup() is not being called so it is not being installed #528 . This will also resolve #462
=> Call the dashboard setup so that it is installed

data_node/esg_dashboard.py, esgf_utilities/esg_functions.py
This will add, and replace duplicates, in the `local.env` from `os.environ` each time an executable is called. This is to resolve #534
=> Get the current environment every call using os.environ

data_node/esg_dashboard.py, esgf_utilities/esg_functions.py
The dashboard install was incomplete. These changes do several things. 
First the download and extraction of `.war` files is a very common patter in the installer. The basic steps of download, extract and change ownership are taken here. This function could be moved to a better place, like esg_functions, to be referenced from other components.
Second, using the new `download_extract` functionality, the `esgf-dashboard.war` file is now being installed into the webapps.
Third, the python sub-component of the dashboard is being downloaded and installed with `easy_install`. This sub-component is used to setup the dashboard database.
Fourth, the startup process `ip.service` needs `liblzma.so.5`. This library is currently only being installed to the conda environment lib directory.
Fifth, the …
=> Dashboard fixes

esg-autoinstall, esg-autoinstall.template
This adds the ability to use "--install-local-certs" and
"--install-keypair" with the autoinstall script.  The changes are
fully backwards compatible as the existing behaviour (no command
line options supplied) is unchanged.
=> Add support to autoinstall for installing certificates

esg-autoinstall
If the compute role is not selected, then under certain conditions
the installer prompts to install it anyway.  Apart from the expect
script not expecting this, if the administrator didn't request the
compute role then obey their request (even if they're wrong :) ).
=> Don't install compute role unless explicitly requested

esg-node
On a clean install, conda was choosing to install Python 3 so be
explicit about what we want.
=> Ensure that Python 2.7 is installed for CDAT

base/esg_postgres.py, data_node/esg_dashboard.py
esgcet uses `pg_config` to determine the version of postgres installed when it is installed. `pg_config` is part of `postgresql-devel`. It is simpler to have it be installed in the postgres module.
=> postgresql-devel is required by both the dashboard and esgcet

base/tomcat_conf/setenv.sh, data_node/thredds.py
At runtime thredds needs to know where libnetcdf.so and its
dependencies are by looking at the LD_LIBRARY_PATH variable. The
conda package "netCDF4" installs the shared object file into the
library directory of the conda environment.
This has been ready for awhile, but unable to test as the VM is unusable right now due to high CPU usage.
=> Do not use system netcdf library, use the version in the conda env

idp_node/mapapp/myproxy-certificate-mapapp, idp_node/mapapp/openid_retriever.py, idp_node/myproxy.py
This is to replace the old java application that performed this process and will resolve #589 and #482. It still needs to be copied into place, `/esg/config/myproxy/`, by the installer.
=> A new process for mapping usernames to openids

esg_bootstrap.sh
`cmor` was not being installed and `esgf-publisher` depends on `cmip6_cv` which is lives in `cmor`. It is now being installed in the bootstrapper, when the `esgf-pub` conda environment is created. This is to resolve #603 .
=> Install cmor for use by the publisher, requires 'cmip6_cv

idp_node/myproxy.py
The old installation process was overwriting the new version of the script. This removes the old installation process.
=> Remove old installation of extension app

base/esg_apache_manager.py, esg_node.py, esgf_utilities/esg_cli_argument_manager.py
Since certificates are installed at the end of the installation
process, starting here will cause them to not be properly
discovered. This allows the start at the end to start httpd.
=> Do not start apache until end of installer or via start flag

base/esg_tomcat_manager.py
This original change was made without the knowledge of how the truststore worked.
=> Revert to using default truststore password

esg_init.py
This is to resolve #617 . After moving to version 3.5.4 of esg-publisher, errors began occurring (#617). This was a result of the re-initialization of thredds that `esgsetup` does in 3.5.4. Tag v2.6a0 has this step removed from `esgsetup`. This was done by @sashakames .
=> No longer run re-initialize thredds

base/esg_apache_manager.py, esgf_utilities/esg_cli_argument_manager.py, index_node/solr.py
The output when starting was giving bad information regarding the status of solr. Theses changes are intended to give the correct information to the user.
=> Properly check if solr is running and cleanup unused imports

esg-node
By default, NTP has been replaced by Chrony on RHEL/CentOS 7.
=> If Chrony is running then don't attempt to start NTP

esgf_utilities/esg_cert_manager.py
The zero serial number was causing SSL connections to the host to fail, if the host did not provide their own certificates.
=> Generate a random number for the serial number of the new certificate

esgf_utilities/CA.py
The zero serial that was replaced previously was not the one causing the problem, probably okay, maybe good, that that one was changed as well. This should resolve the browsers rejecting this certificate because of duplicate serial number.
=> Use non-zero serial number when signing the new cert

data_node/esg_dashboard.py
This may be OS dependent, but that is not a concern of the project at the moment. With the `/usr` prefix this should allow the esgf-dashboard-ip process to find all the needed files. This has been tested manually. This is to continue to resolve #615 and #462.
=> This is the required prefix if yum install geoip libraries via geoip-devel

base/esg_apache_manager.py, data_node/esg_publisher.py
The symbolic link is not needed as we are not install postgres 9.x.
=> Remove the creation of the pg_config symlink and unused import

docs/autoinstall_usage.rst, docs/index.rst, esgf.properties.template
I created a documentation page with brief descriptions of the properties found in the esgf.properties (aka autoinstall) file so that users can reference this when configuring their node.  The documentation can be found here: https://esgf.github.io/esgf-installer/autoinstall_usage.html
I'm opening this PR in case either of you can see improvements that can be maded to the descriptions.
=> created autoinstall properties documentation page

esg_bootstrap.sh
esgprep requires 'requests==2.19.1'. pip does not resolve
dependencies across multiple pip install commands, it only warns
about them. 'requests' 2.20.0 was released Oct 18th 2018.
=> Pin the requests version to version required by esgprep

esgf_utilities/esg_truststore_manager.py
Although the existing truststore insert functionality was not broken, it was slow and outputted potentially misleading information. It would have Java exceptions saying each alias did not exist. While this was a result of an attempted deletion, it still appeared there was a problem. These changes use the `pyjks` module, as well as the `OpenSSL` module, to insert certificates into the truststore.
=> Truststore insert

esg_node.py
This failing chown is a consequence of removing `esg_init.py`. That is why I am reusing this branch.
=> Remove unneeded, failing, chown and remove misleading print

data_node/thredds.py, esg_bootstrap.sh, esgf_utilities/esg_truststore_manager.py
These are changes that were made to resolve issues that arose when testing a data-only install. For now we are no longer retrieving the the IDP peers certificate to be inserted into our trust store as the tool to do this is outdated and requires manual user input. @sashakames has said sites use commercial certificates that have been signed by trusted certificate authorities.
=> Data only fixes

base/esg_java.py, esg_node.py
The "esg.root.url" property was not being found as it was part of a global variable. This caused it to be looked for before it is populated in `esg_node.py`.
=> Resolve unfound property issue.

esg_bootstrap.sh
This has become a perpetual problem. This problem could be resolved by separating the installer and publisher environments. This solution will have to be applied in the future.
=> Align the requests version with that in esgprep, again

esg_config.yaml, index_node/solr.py
The solr version was being stored in the solr.py file instead of the esg_config.yaml file.  This deviated from the rest of the version tracking so the solr version was moved to esg_config.yaml
=> moved solr version setting to esg_config.yml; resolves #686

esg-autoinstall, esg-autoinstall.template
Nodes that use a separate Globus/GridFTP DTN deployed outside the ESGF stack are unlikely to want ESGF to register itself automatically as a Globus endpoint. Note that the default behaviour is unchanged by this patch.
=> Support disabling automatic registration of Globus endpoint

esg-node
@davidhassell tells me that cdf2cim 0.3.0.0 is ready. Bumping version in ESGF installer (though surprised to find that it is defined in `esg-node` rather than in `esg-init`).
=> require cdf2cim 0.3.0.0

esg-init
This ensures that the system-default openssl is accorded higher priority than the openssl installed by conda.
Caveat: if any conda-installed packages are expected to override the system-defaults, due to the conda bin environment occuring first in the PATH variable, this will now fail.
=> This fixes issues 709, 710, and 701.
