ESGF/esgf-installer

esg-functions, esg-node
This time, we complete the node manager installation but remove the web app at end.
make change for aims1 mirror, mirror use for yum repo.
=> Remove components, add mirror at llnl, pip

esg-node
add httpd httpd-devel mod_ssl to yum install
=> more dependencies

esg-purge.sh, setup-autoinstall
I noticed the following was lacking, so here are the corrections.
=> minor fix of things

esg-init
publisher has changes to thredds urls recommended by Luca
=> update publisher version for TDS 5

esg-node
Need to copy log4j-1.2.7.jar to the distrib server
=> add one more jar

esg-node
adds the wheel permission to root admin and role 6 'user'
=> psql inserts

esg-init, esg-node
The template fixes LAS paths and some cmip5 publication config defaults
sed cmds fix LAS urls.
=> new pub template, seds

jar_security_scan
This code could use a bit of cleanup still, but it's usable.
=> First edition of jar security scanner

esg-autoinstall, esg-autoinstall-testnode, esg-autoinstall.template, esg-purge.sh
Expect script tested as working for an index node
=> esg-autoinstall

esg-functions, esg-node
Hi guys, a couple small things I thought worth adding, and just took the time to get them in.
1) add httpd to the node status check
2) check for the existence of the input files for --install-keypair
=> add Apache status to --status, check cert install input

esg-init
Needed to revert esgscan_dir to filter .nc files as that got removed by mistake.
=> Next publisher version

esg-autoinstall
this resolves the off-by-one issue with the tomcat username and allowed IPs
=> Don't respond to 'Is this ok' prompt

esg-node
=> remove bad language from the comments

globus/esg-globus
see comment attached to the (only) commit
=> fix logic re whether bind mount already exists

esg-autoinstall, esg-autoinstall.template, esg-node
Per https://github.com/ESGF/esgf-installer/issues/271
=> fix for issue 271

esg-functions, esg-node
esgf do not use any more esgf-httpd status but httpd (with a different config file)
=> now use httpd service

base/esg_apache_manager.py, base/esg_java.py, esgf_utilities/esg_functions.py, tests/test_esg_apache.py, tests/test_esg_functions.py, tests/test_esg_java.py
This could be a potentially lengthy pull request so I'm adopting the work-in-progress (!WIP) convention. I'm adding unit tests along the way as well.
One thing this could potentially allow us to do is to get cross-platform compatibility. Plumbum has a get() methods that can take a list of binaries to search for if the initial one isn't found.  So when we need to install something from a Unix package manager, we could try to find yum first and then try to use apt-get in the exception block to cover Ubuntu/Debian
=> !WIP:Plumbum

base/esg_apache_manager.py, base/esg_java.py, data_node/esg_publisher.py, esgf_utilities/esg_functions.py, tests/test_esg_apache.py, tests/test_esg_functions.py, tests/test_esg_java.py
This uses the new plumbum module to install the esgcet package from the git repository it lives in. @William-Hill Also recall the convention that if you approve and I didn't assign myself, feel free to merge it.
=> Pip install git

base/esg_postgres.py, base/esg_tomcat_manager.py, esgf_utilities/esg_functions.py, tests/test_esg_apache.py, tests/test_esg_postgres.py
Using Plumbum for better exception handling and cleaner code
=> Replaced subprocess with Plumbum (via call_binary function) in base module

base/esg_tomcat_manager.py, base/tomcat_conf/server.xml.tmpl
These changes will fix issues arising post-installation as specified in #518 and #499 .
=> Template server.xml, set ESGF_HOME and clean up code

data_node/esg_dashboard.py, data_node/esg_publisher.py, data_node/thredds.py, esgf_utilities/esg_functions.py, esgf_utilities/esg_questionnaire.py
Replaces subprocess calls where possible with plumbum (via call_binary utility function)
=> Plumbum data node

index_node/solr.py
=> removed hardcoded URL

esg_bootstrap.sh
These changes have the conda command only run once. This gets rid of the second run of "Solving Environment" and improves the run time of the bootstrapper
=> Solve env once

idp_node/myproxy.py
=> 'myproxy' is not a service that exists, it is 'myproxy-server'

.circleci/config.yml, esg_init.py
adding .circleci/config.yml -- currently the build in circleci will launch a docker image, run esg_bootstrap.sh and not running any unit tests yet.
I have to run each unit test, and see which one is working and add it to the branch.
=> Add .circleci/config.yml

esg_node.py, esgf.properties.template, esgf_utilities/esg_cert_manager.py, esgf_utilities/esg_cli_argument_manager.py, esgf_utilities/esg_keystore_manager.py
=> 572 and 573

base/esg_postgres.py, data_node/esg_dashboard.py
Reverts ESGF/esgf-installer#587; Reverting so that i can be a part of v3.0a2
=> Revert "postgresql-devel is required by both the dashboard and esgcet"

base/esg_postgres.py, data_node/esg_dashboard.py
Reverts ESGF/esgf-installer#593
=> Revert "Revert "postgresql-devel is required by both the dashboard and esgcet""

base/esg_postgres.py, base/esg_tomcat_manager.py, esg_node.py, esgf_utilities/CA.py, esgf_utilities/esg_cert_manager.py, esgf_utilities/esg_cli_argument_manager.py, esgf_utilities/esg_functions.py, esgf_utilities/esg_keystore_manager.py, esgf_utilities/esg_truststore_manager.py
=> 585-586-588

index_node/solr.py
The origins of this PR are reported in #606.
=> Remove inner quotes as plumbum adds quotes to arguments itself

base/esg_postgres.py
Added schema default param for #580
=> added schema option to backup_db(); resolves #580

data_node/esg_dashboard.py, esgf_utilities/esg_cli_argument_manager.py, esgf_utilities/esg_env_manager.py, esgf_utilities/esg_property_manager.py
This PR has number of changes and improvements that not only make it more possible to start esgf-dashboard-ip, but also will be useful to other parts of the installer. The goal is to resolve #615 and #462.
=> Make needed changes and improvements to start esgf-dashboard-ip

data_node/thredds.py, esgf.properties.template, tests/mock_files/mock_esgf.properties
#629 initially suggested a refactor but after discussing with Sasha, the feature is really never used thus is being deleted.
=> removed code for adding additional Thredds tomcat users; addresses #629

esgf_utilities/esg_cli_argument_manager.py, index_node/esg_search.py, index_node/solr.py
This functionality had not yet been implemented and is a required command line management option. This has been manually tested.
=> Shard management

base/apache_conf/esgf-httpd.conf, data_node/esg_dashboard.py
=> Set proper permissions on /var/run and reinstate WSGIProcessGroup

data_node/esg_dashboard.py, esg_node.py, esgf_utilities/esg_functions.py
The intention of this branch was debug why the esgf-dashboard directory was not present in the tomcat webapps directory. After some debugging it was discovered that the directory was simply being removed at the end of the installation. So, it is simply no longer being installed.
=> Dashboard install log

esg_config.yaml, idp_node/esg_security.py
Updated the version of esg_security in the yaml config file.
=> updated esg_security to latest version (2.7.18)

idp_node/idp.py
Fixed some issues with the SLCS installation.
=> added conda env check; remove uncommitted changes from playbook in order to check out branch
